### ISSUE TITLE
maven resource not available

### ISSUE THREAD

**Issue by AaronVanStappen** [SolaceSamples/solace-samples-java-new#3]
It seems that the package 'com.solace.messaging' cannot be found. I want to use the MessagingService, however, I cannot seem to find the correct Maven dependency. Even when I clone the project locally, Maven cannot find the corresponding dependencies.

**Comment by Mrc0113** [comment]
Hi @AaronVanStappen, 
The API is currently in early access to members of the Solace Dev Community; so it can't yet be retrieved via maven. You can download the API in this post: https://solace.community/discussion/643/early-access-now-available-for-the-new-java-messaging-api
