### ISSUE TITLE
Any ETA on Distributed Tracing ?

### ISSUE THREAD

**Issue by HookWoods** [SolaceSamples/solace-samples-java-new#34]
Hello, my company started using Datadog, and actually the only part that isn't profiled in the APM is Solace.
I started working on manual instrumentation with OTEL and just saw Solace has added support for TextMapPropagator in JCSMP but not in these libs yet.

Is there any ETA on when will this be released? Thank you!

**Comment by Mrc0113** [comment]
Hi @HookWoods, 
Thank you for letting us know. It is definitely on the roadmap and our API team is currently planning out the delivery calendar for the remainder of the year. I would also recommend opening a support ticket so they mark your interest and will be sure to follow up with you ASAP when it is available. 

I will leave this open until I have a ballpark estimate.

**Comment by Mrc0113** [comment]
Hi @HookWoods, hopefully you already found this was avaialble. But if not you can find the docs here: https://docs.solace.com/API/API-Developer-Guide-Java/Java-API-Distributed-Tracing.htm#Instrumenting-Java-Distributed-Tracing

Sorry I forgot to update it!
