### ISSUE TITLE
Solace Tutorial links are broken

### ISSUE THREAD

**Issue by dev-mansonthomas** [SolaceSamples/solace-samples-java-new#8]
Hi,

The links that seems to point to this repo on this page : https://tutorials.solace.dev/java are all broken (404)

Thomas.

**Comment by Mrc0113** [comment]
thanks @dev-mansonthomas; resolved by this PR: https://github.com/SolaceDev/solace-dev-tutorials/pull/76
CI/CD in process and should be live any second now ;)
